server:
  port: 8081
spring:
  application:
    name: sst
  main:
    allow-bean-definition-overriding: true
  task:
    execution:
      thread-name-prefix: sst-task-
      pool:
        core-size: 1
        max-size: 20
        queue-capacity: 1000
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: test@pwd
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.timezone.default_storage: NORMALIZE
      hibernate.type.preferred_instant_jdbc_type: TIMESTAMP
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
      hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
      hibernate.cache.use_minimal_puts: true
      hibernate.cache.hazelcast.instance_name: sst-cache
      hibernate.cache.hazelcast.use_lite_member: true
  kafka:
    bootstrap-servers: localhost:9092
application:
  api-docs:
    default-include-pattern: ${server.servlet.context-path:}/api/**
    management-include-pattern: ${server.servlet.context-path:}/management/**
    title: Test Application API
    description: SpringBoot Scaffolding App API documentation
    version: 0.0.1
    terms-of-service-url:
    contact-name: "Elyes Ben Salah"
    contact-url:
    contact-email: "bselyes@gmail.com"
    license: Apache-2.0
    license-url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
    servers:
      - url: "http://localhost:8081/api"
        description: "Development server"
      - url: "https://localhost:8081/api"
        description: "Development server with TLS"
  security:
    authentication:
      jwt:
        base64-secret: vapMht8V6g24zO4P6qDou4OQFaPgkcHMhCNTyF9UJi5kp0VH8ayv2YeeUIuUrFiqH/BWITaC/2FHRX+PQcvSIQ==
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  cache: # Cache configuration
    hazelcast: # Hazelcast distributed cache
      time-to-live-seconds: 3600
      backup-count: 1
