logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO
    tn.example.sst: DEBUG
spring:
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    user: test
    password: test@pwd
    url: jdbc:postgresql://localhost:5432/test
    schemas: test
    enabled: true
