name: dev-services
services:
    kafka:
        image: confluentinc/cp-kafka:7.5.2
        ports:
            - 9092:9092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_ADVERTISED_HOST_NAME: kafka
    zookeeper:
        image: confluentinc/cp-zookeeper:7.5.2
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            - 'ES_JAVA_OPTS=-cd Xms256m -Xmx256m'
            - 'discovery.type=single-node'
            - 'xpack.security.enabled=false'
        healthcheck:
            test: [ 'CMD', 'curl', '-f', 'http://localhost:9200/_cluster/health?wait_for_status=green&timeout=10s' ]
            interval: 5s
            timeout: 10s
            retries: 10
